export const pageRoot: string;
export const topHeader: string;
export const topHeaderTitle: string;
export const shellLayout: string;
export const sidebar: string;
export const sidebarActions: string;
export const sidebarBtn: string;
export const sidebarBtnSecondary: string;
export const sidebarDivider: string;
export const sidebarSection: string;
export const sidebarStatus: string;
export const sidebarStatusLabel: string;
export const centerPanel: string;
export const centerContent: string;
export const brand: string;
export const brandTitle: string;
export const brandSubtitle: string;
export const workspaceContext: string;
export const workspaceContextTitle: string;
export const workspaceContextText: string;
export const workspaceContextHint: string;
export const welcomeSection: string;
export const welcomeSectionTitle: string;
export const sectionDivider: string;
export const recentList: string;
export const recentRow: string;
export const recentRowIcon: string;
export const recentRowCenter: string;
export const recentRowName: string;
export const recentRowMeta: string;
export const recentRowRight: string;
export const recentRowTime: string;
export const recentRowHint: string;
export const emptyRecent: string;
export const createFormPanel: string;
export const createFormInner: string;
export const createFormHeader: string;
export const createFormIconWrap: string;
export const createFormTitle: string;
export const createFormHint: string;
export const createFormDivider: string;
export const createFormSectionLabel: string;
export const createFormSectionDivider: string;
export const createFormFieldRow: string;
export const createFormFieldHalf: string;
export const createFormSegmented: string;
export const createFormActions: string;
export const createFormBackBtn: string;
export const createFormSubmitBtn: string;
export const createFormSubmitReady: string;

declare const styles: {
  pageRoot: string;
  topHeader: string;
  topHeaderTitle: string;
  shellLayout: string;
  sidebar: string;
  sidebarActions: string;
  sidebarBtn: string;
  sidebarBtnSecondary: string;
  sidebarDivider: string;
  sidebarSection: string;
  sidebarStatus: string;
  sidebarStatusLabel: string;
  centerPanel: string;
  centerContent: string;
  brand: string;
  brandTitle: string;
  brandSubtitle: string;
  workspaceContext: string;
  workspaceContextTitle: string;
  workspaceContextText: string;
  workspaceContextHint: string;
  welcomeSection: string;
  welcomeSectionTitle: string;
  sectionDivider: string;
  recentList: string;
  recentRow: string;
  recentRowIcon: string;
  recentRowCenter: string;
  recentRowName: string;
  recentRowMeta: string;
  recentRowRight: string;
  recentRowTime: string;
  recentRowHint: string;
  emptyRecent: string;
  createFormPanel: string;
  createFormInner: string;
  createFormHeader: string;
  createFormIconWrap: string;
  createFormTitle: string;
  createFormHint: string;
  createFormDivider: string;
  createFormSectionLabel: string;
  createFormSectionDivider: string;
  createFormFieldRow: string;
  createFormFieldHalf: string;
  createFormSegmented: string;
  createFormActions: string;
  createFormBackBtn: string;
  createFormSubmitBtn: string;
  createFormSubmitReady: string;
};
export default styles;
